language: node_js
node_js:
- node
- 'lts/*'
- '6'
- '4'
install: npm install
before_install:
- if [[ `npm -v` = 2* ]]; then npm i -g npm@3; fi
notifications:
  email:
    on_success: never
    on_failure: change